repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v1.2.3
        hooks:
            -   id: detect-private-key
            -   id: no-commit-to-branch
                args: [--branch, master, --branch, develop]
            -   id: flake8
