version: 2.1

workflows:
  branch_tests:
    jobs:
      - tests:
          name: Run all tests under emulator
jobs:

  tests:
    docker:
        - image: javierluna/datastorm-test-env:255.0.0-3.6.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install poetry
            make dependencies
      - run:
          name: Run tests
          command: |
            . env/bin/activate
            make tests

      - run:
          name: Lint code
          command: |
            . env/bin/activate
            make lint-code
