version: 2.1

workflows:
  branch_tests:
    jobs:
      - tests:
          name: Run all tests under emulator
      - static-analysis:
          name: Run linting and type hinting checks
jobs:

  tests:
    docker:
        - image: javierluna/datastorm-test-env:255.0.0-3.6.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install poetry
            make dependencies
      - run:
          name: Run tests
          command: |
            . env/bin/activate
            make tests

  static-analysis:
      docker:
          - image: circleci/python:3.6
      steps:
          - checkout
          - run:
              name: Install dependencies
              command: |
                python3 -m venv env
                . env/bin/activate
                pip install poetry
                make dependencies
          - run:
              name: Linting
              command: |
                . env/bin/activate
                make lint
          - run:
              name: Type hinting
              command: |
                . env/bin/activate
                make type-check
